[package]
name = "Cryptopals"
version = "0.1.0"
authors = ["Daniel Murphy <danwright91@gmail.com>"]

[dependencies]

[lib]
name = "cryptopals_lib"
path = "src/lib.rs"

[[bin]]
name = "cryptopals_bin"
path = "src/bin.rs"